# configs/app_config.yaml

# BioViT3R-Beta Application Configuration
# Main configuration file for all system components

app:
  name: "BioViT3R-Beta"
  version: "1.0.0-beta"
  description: "Advanced Plant Analysis with VGGT 3D Reconstruction and AI Assistance"
  debug: false
  log_level: "INFO"

# Gradio Interface Configuration
interface:
  title: "🌱 BioViT3R-Beta: Advanced Plant Analysis Platform"
  description: "AI-powered plant health assessment, 3D reconstruction, and agricultural insights"
  theme: "default"
  show_api: true
  show_error: true
  server_name: "0.0.0.0"
  server_port: 7860
  share: false
  auth: null  # Set to [["username", "password"]] for basic auth
  max_threads: 4
  favicon_path: null

# Model Configuration
models:
  # VGGT 3D Reconstruction
  vggt:
    model_name: "VGGT"
    device: "cuda"  # cuda, cpu, auto
    precision: "fp16"  # fp32, fp16, bf16
    cache_dir: "models/vggt"
    download_url: "https://github.com/VGGT/releases/download/v1.0/vggt_checkpoint.pth"
    input_size: [480, 480]
    output_format: "ply"  # ply, obj, pcd
    max_points: 100000
    mesh_reconstruction: true
    texture_mapping: false
    
  # Fruit Detection Models
  fruit_detection:
    acfr_model:
      model_path: "models/fruit_detection/acfr_faster_rcnn.pth"
      config_path: "models/fruit_detection/acfr_config.yaml"
      confidence_threshold: 0.5
      nms_threshold: 0.3
      max_detections: 100
      classes: ["apple", "fruit"]
      
    minneapple_model:
      model_path: "models/fruit_detection/minneapple_yolov8.pt"
      confidence_threshold: 0.6
      nms_threshold: 0.4
      max_detections: 200
      classes: ["apple"]
    
    ensemble_mode: true  # Use both models and combine results
    ensemble_weights: [0.6, 0.4]  # ACFR, MinneApple
    
  # Plant Health Classification
  health_classification:
    model_path: "models/health_classification/plant_health_resnet50.pth"
    classes: ["healthy", "diseased", "pest_damage", "nutrient_deficiency", "water_stress"]
    confidence_threshold: 0.7
    input_size: [224, 224]
    preprocessing:
      normalize: true
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]
      
  # Growth Stage Classification  
  growth_classification:
    model_path: "models/growth_classification/growth_stage_efficientnet.pth"
    classes: ["seedling", "vegetative", "flowering", "fruit_development", "ripening", "senescence"]
    confidence_threshold: 0.6
    input_size: [256, 256]
    
  # Biomass Estimation
  biomass_estimation:
    method: "volumetric"  # volumetric, allometric, ml_regression
    allometric_coefficients:
      apple:
        a: 0.0847  # Species-specific coefficient
        b: 2.4567  # Scaling exponent
      default:
        a: 0.0750
        b: 2.5000
    density_kg_m3: 0.65  # Average plant tissue density
    volume_correction_factor: 0.85  # Account for hollow spaces

# Data Processing Configuration
data_processing:
  # Image Preprocessing
  image_preprocessing:
    resize_method: "pad"  # resize, crop, pad
    target_size: [512, 512]
    normalize: true
    background_removal: false
    enhancement:
      contrast: 1.0
      brightness: 0.0
      saturation: 1.0
      gamma: 1.0
      
  # Video Processing
  video_processing:
    max_frames: 30
    frame_sampling: "uniform"  # uniform, keyframe, adaptive
    temporal_analysis: true
    optical_flow: false
    
  # Data Augmentation (Training)
  augmentation:
    enabled: true
    horizontal_flip: 0.5
    vertical_flip: 0.2
    rotation_range: 15
    zoom_range: 0.1
    brightness_range: 0.2
    contrast_range: 0.2
    noise_factor: 0.05

# IBM Watsonx AI Configuration
ibm_watsonx:
  # Connection Settings
  api_key: "${IBM_WATSON_APIKEY}"  # Environment variable
  project_id: "${IBM_PROJECT_ID}"  # Environment variable  
  url: "${IBM_WATSON_URL:https://us-south.ml.cloud.ibm.com}"
  
  # Model Settings
  model_id: "ibm/granite-13b-chat-v2"
  
  # Generation Parameters
  generation_params:
    max_new_tokens: 512
    temperature: 0.7
    top_p: 0.9
    top_k: 50
    repetition_penalty: 1.1
    length_penalty: 1.0
    
  # Chat Configuration
  chat:
    max_history_length: 50
    context_window: 4000
    system_prompt: |
      You are an expert agricultural AI assistant specializing in plant health assessment, 
      crop management, and precision agriculture. Provide accurate, scientifically-grounded 
      responses focused on practical agricultural applications.
    
    enable_context: true
    context_retention_hours: 24
    
  # Timeout and Retry Settings
  timeout_seconds: 30
  max_retries: 3
  retry_delay: 2

# Database Configuration
database:
  # SQLite for local development
  type: "sqlite"
  database: "data/biovit3r.db"
  
  # PostgreSQL for production (when available)
  # type: "postgresql"
  # host: "${DB_HOST:localhost}"
  # port: "${DB_PORT:5432}"
  # database: "${DB_NAME:biovit3r}"
  # username: "${DB_USER:biovit3r}"
  # password: "${DB_PASSWORD}"
  
  # Connection Pool
  pool_size: 5
  max_overflow: 10
  pool_timeout: 30
  
# Caching Configuration
cache:
  # Redis Configuration
  type: "redis"  # redis, memory, file
  host: "${REDIS_HOST:localhost}"
  port: "${REDIS_PORT:6379}"
  db: 0
  password: "${REDIS_PASSWORD:}"
  
  # Cache TTL (seconds)
  model_cache_ttl: 3600      # 1 hour
  result_cache_ttl: 1800     # 30 minutes
  image_cache_ttl: 7200      # 2 hours
  
  # Memory fallback
  memory_cache_size: 100     # MB
  
# File Storage Configuration
storage:
  # Local storage paths
  uploads_dir: "data/uploads"
  outputs_dir: "data/outputs"
  cache_dir: "data/cache"
  logs_dir: "logs"
  
  # File size limits (MB)
  max_image_size: 50
  max_video_size: 500
  max_batch_size: 1000
  
  # Supported formats
  supported_image_formats: [".jpg", ".jpeg", ".png", ".bmp", ".tiff", ".webp"]
  supported_video_formats: [".mp4", ".avi", ".mov", ".mkv", ".webm"]
  
  # Cleanup policy
  cleanup_after_days: 7
  auto_cleanup: true

# Security Configuration
security:
  # Rate limiting
  rate_limit:
    enabled: true
    requests_per_minute: 60
    burst_limit: 10
    
  # File upload security
  scan_uploads: true
  allowed_mime_types: 
    - "image/*"
    - "video/*"
  max_file_size: 52428800  # 50MB in bytes
  
  # API Security
  api_key_required: false
  cors_enabled: true
  cors_origins: ["*"]

# Monitoring and Logging
monitoring:
  # Metrics collection
  metrics_enabled: true
  metrics_port: 9090
  
  # Health checks
  health_check_interval: 60  # seconds
  
  # Performance monitoring
  track_inference_time: true
  track_memory_usage: true
  track_gpu_usage: true
  
# Logging Configuration
logging:
  level: "INFO"  # DEBUG, INFO, WARNING, ERROR, CRITICAL
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  
  # File logging
  file_logging: true
  log_file: "logs/biovit3r.log"
  max_file_size: 10485760  # 10MB
  backup_count: 5
  
  # Console logging
  console_logging: true
  
  # Structured logging
  json_logging: false
  
# Development Configuration
development:
  # Hot reload
  auto_reload: true
  
  # Debug features
  enable_profiling: false
  enable_memory_tracking: false
  
  # Mock services (for testing without external dependencies)
  mock_ibm_watsonx: false
  mock_models: false

# Production Configuration
production:
  # Performance optimizations
  model_caching: true
  result_caching: true
  batch_processing: true
  
  # Resource limits
  max_concurrent_requests: 10
  request_timeout: 300
  
  # Monitoring
  error_reporting: true
  performance_monitoring: true
  
  # Security
  force_https: true
  secure_headers: true